services:
  - type: web
    name: exam-system-api
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    healthCheckPath: /api/auth/test
    envVars:
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PYODBC_INCLUDE
        value: /usr/local/include/
      - key: PYODBC_LDFLAGS  
        value: -L/usr/local/lib/
      - key: ADMIN_PASSWORD
        sync: false 